services:
  es3_database:
    container_name: es3_database
    image: mongo:7
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - es3_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: app_db
    env_file:
      - ../.env

  es3_api:
    container_name: es3_api
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: yarn run start:dev
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ../src:/home/node/app/src
      - ../.env:/home/node/app/.env
    env_file:
      - ../.env
    depends_on:
      - es3_database

volumes:
  es3_data:
